name: Arduino CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v1
    - name: Check out code
      uses: actions/checkout@v2
    - name: Compile Arduino Sketch
      uses: arduino/compile-sketches@v3
      with:
        fqbn: arduino:avr:mega
        sketch-names: 'Transmission_Controller/main/main.ino'
