name: Arduino CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v1
    - name: Check out code
      uses: actions/checkout@v4
    - name: Compile Sketch
      run: arduino-cli compile --fqbn "arduino:avr:mega" "Transmission_Controller/main/main.ino"
